### ISSUE TITLE
Next generation implementation

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-ft-icons#90]
As discussed elsewhere, there's consensus that we should move away from an icon font. I thought I'd start this to document functionality that's available now, potential requirements and limitations for the next version and ideas for implementation

### Current functionality

- font can be specified using either sass or css class & build service
- font can be coloured arbitrarily. This can be achieved when using build service to define the fonts and is trivial to do for e.g. :hover states
- font is specified as a background image - it is not treated as content - and uses `<i class...>`, so no complex template needed, but no accessibility features such as alt text
- Supported all the way back to IE7

### Potential additional/modified requirements
- **NO ICON FONT**
- icon should be treated as content, i.e. not applied using css background image 
- icon can be coloured in the FT palette via the build service (potential to use arbitrary colours using sass/js)
- Support back to ie8/9, with some accessible text fallback
- Reasonably sized set of 'next' icons to replace the existing ones entirely (old ones still available in 'legacy' namespace)
- use mixins not @extend
- standardise icon sizes or have a convention for indicating non-squareness
- icons with predefined, unalterable colours, supporting multiple colours

Please add comments on the requirements and implementation ideas below

**Comment by wheresrhys** [comment]
No idea how workable this would be, but based on the assumption that icons are content, we use a `<ft-icon alt=“star” type=“clock”>` custom element. Eventually this would be a web component bringing in an svg which can be coloured, sized etc.  with whatever good stuff becomes available in future browsers. Can fallback to being styled using CSS and SVG background image for now

**Comment by pornel** [comment]
1. Consider *not* using an icon font. The advantages of icon fonts (working around lack of SVG support, and "spriting" for HTTP/1.1) are becoming less and less relevant. Individual SVG files sent over HTTP/2 are easier to manage and may be faster (the browser needs to load only the icons that are used, instead of a font with _all_ of them).

2. If you're using an icon font, **use custom ligatures** that replace words with icons. Take a close look at this font: https://symbolset.com/

With custom ligatures you *don't* use high unicode codepoints that are read and rendered as garbage without the font. You use simple *ASCII text* and the font essentially does find'n'replace of readable words with symbols, which is a purely decorative technique, so it's completely invisible to screen readers, copy&paste, bots, etc. So it gives you ideal accessibility, not only for screen readers only (as hidden text hacks), but also for visual rendering in case when the font doesn't load (due to content blockers, slow network, etc.)

**Comment by AlbertoElias** [comment]
I think using SVGs is what we're aiming for :)

**Comment by wheresrhys** [comment]
@kornel getting rid of the icon font is the number one requirement I think (Will add as an explicit item)

**Comment by wheresrhys** [comment]
although that custom ligatures thing looks really cool

**Comment by wheresrhys** [comment]
and re the web component idea my thoughts are you use a custom element now, and this won't actually break anything as html is already extensible as far as defining tags goes... just not when it comes to defining custom behaviour.

So when eventually web components are mature enough we can switch from applying the icon using css to using a proper webcomponent, and the end user won't need to go round refactoring all their templates

**Comment by Kornel** [comment]
@wheresrhys I don't think you've used the right handle (@...) although I'm quite I intrigued by this discussion, as I have no idea what an icon font is :) I'll definitely read a bit about that

**Comment by wheresrhys** [comment]
welcome aboard :-)

**Comment by i-like-robots** [comment]
I'm quite happy with keeping icons as presentational rather than content (though the `<ft-icon>` sounds :sunglasses:).

Personally I'm happy with this sort of thing:

```html
<span class="o-icon o-icon--after o-icon--text o-icon--red o-icon--right-arrow">Do the thing!</span>
```

Which might be something like:

```css
.o-icon--before::before,
.o-icon--after::after {
  content: '';
  display: inline-block;
  background: transparent no-repeat;
  background-size: 100%:
}

/* size variations could be also be --S --XL etc */
.o-icon--text {
  width: 1em;
  height: 1em;
  vertical-align: middle;
}

/* relies on spriting SVG vertically (not horizontally because background size) */
.o-icon--red {
  background-position: 0 -25%;
}

.o-icon--right-arrow {
  background-image: url('path/to/image/service/with/colour/palette/variants.svg');
}
```

Spriting SVGs for colour variations is fairly simple if you're working with paths*

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="320" height="64" viewBox="0 0 320 64">
<defs>
<g id="search">
  <path d="..."></path>
</g>
</defs>

<g fill="#333">
  <use xlink:href="#search" transform="translate(0 0)"></use>
</g>

<g fill="#F00">
  <use xlink:href="#search" transform="translate(0 32)"></use>
</g>

<g fill="#FFF">
  <use xlink:href="#search" transform="translate(0 64)"></use>
</g>
</svg>
```

* I used Icomoon, OK

**Comment by kavanagh** [comment]
Note that there's a problem with the SVG spec that means you cannot use an SVG Symbol (via Use/View) from another domain. Adding CORS headers doesn't help either. [See the Chromium issue for more details](https://code.google.com/p/chromium/issues/detail?id=470601).

So doing this doesn't work:

```html
<button>
<svg><use xlink:href="https://build.origami.ft.com/files/o-ft-icons/v4#save-icon"></use></svg>
Button label 
</button>
```

And a CSS solutions such as below won't work either

```css
.icon--save {
  background: url(https://build.origami.ft.com/files/o-ft-icons/v4#save-icon) no-repeat center center;
}
```
```html
<button class="icon icon--save">
Button label
</button>
```
